interface JobListing {
  id: string
  jobTitle: string
  jobType: string
  datePosted: string
  applicants: number
  views: number
  status?: string
}
const mockJobListingsData: JobListing[] = [
    {
      id: "1",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Freelance",
      datePosted: "2025-02-10",
      applicants: 0,
      views: 0,
      status: "active",
    },
    {
      id: "2",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Extra Job",
      datePosted: "2025-01-15",
      applicants: 5,
      views: 120,
      status: "active",
    },
    {
      id: "3",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Part time",
      datePosted: "2024-12-20",
      applicants: 10,
      views: 80,
      status: "closed",
    },
    {
      id: "4",
      jobTitle: "Frontend Developer",
      jobType: "Full time",
      datePosted: "2025-02-05",
      applicants: 15,
      views: 200,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "1",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Freelance",
      datePosted: "2025-02-10",
      applicants: 0,
      views: 0,
      status: "active",
    },
    {
      id: "2",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Extra Job",
      datePosted: "2025-01-15",
      applicants: 5,
      views: 120,
      status: "active",
    },
    {
      id: "3",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Part time",
      datePosted: "2024-12-20",
      applicants: 10,
      views: 80,
      status: "closed",
    },
    {
      id: "4",
      jobTitle: "Frontend Developer",
      jobType: "Full time",
      datePosted: "2025-02-05",
      applicants: 15,
      views: 200,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "1",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Freelance",
      datePosted: "2025-02-10",
      applicants: 0,
      views: 0,
      status: "active",
    },
    {
      id: "2",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Extra Job",
      datePosted: "2025-01-15",
      applicants: 5,
      views: 120,
      status: "active",
    },
    {
      id: "3",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Part time",
      datePosted: "2024-12-20",
      applicants: 10,
      views: 80,
      status: "closed",
    },
    {
      id: "4",
      jobTitle: "Frontend Developer",
      jobType: "Full time",
      datePosted: "2025-02-05",
      applicants: 15,
      views: 200,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "1",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Freelance",
      datePosted: "2025-02-10",
      applicants: 0,
      views: 0,
      status: "active",
    },
    {
      id: "2",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Extra Job",
      datePosted: "2025-01-15",
      applicants: 5,
      views: 120,
      status: "active",
    },
    {
      id: "3",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Part time",
      datePosted: "2024-12-20",
      applicants: 10,
      views: 80,
      status: "closed",
    },
    {
      id: "4",
      jobTitle: "Frontend Developer",
      jobType: "Full time",
      datePosted: "2025-02-05",
      applicants: 15,
      views: 200,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "1",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Freelance",
      datePosted: "2025-02-10",
      applicants: 0,
      views: 0,
      status: "active",
    },
    {
      id: "2",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Extra Job",
      datePosted: "2025-01-15",
      applicants: 5,
      views: 120,
      status: "active",
    },
    {
      id: "3",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Part time",
      datePosted: "2024-12-20",
      applicants: 10,
      views: 80,
      status: "closed",
    },
    {
      id: "4",
      jobTitle: "Frontend Developer",
      jobType: "Full time",
      datePosted: "2025-02-05",
      applicants: 15,
      views: 200,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "1",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Freelance",
      datePosted: "2025-02-10",
      applicants: 0,
      views: 0,
      status: "active",
    },
    {
      id: "2",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Extra Job",
      datePosted: "2025-01-15",
      applicants: 5,
      views: 120,
      status: "active",
    },
    {
      id: "3",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Part time",
      datePosted: "2024-12-20",
      applicants: 10,
      views: 80,
      status: "closed",
    },
    {
      id: "4",
      jobTitle: "Frontend Developer",
      jobType: "Full time",
      datePosted: "2025-02-05",
      applicants: 15,
      views: 200,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "1",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Freelance",
      datePosted: "2025-02-10",
      applicants: 0,
      views: 0,
      status: "active",
    },
    {
      id: "2",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Extra Job",
      datePosted: "2025-01-15",
      applicants: 5,
      views: 120,
      status: "active",
    },
    {
      id: "3",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Part time",
      datePosted: "2024-12-20",
      applicants: 10,
      views: 80,
      status: "closed",
    },
    {
      id: "4",
      jobTitle: "Frontend Developer",
      jobType: "Full time",
      datePosted: "2025-02-05",
      applicants: 15,
      views: 200,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "1",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Freelance",
      datePosted: "2025-02-10",
      applicants: 0,
      views: 0,
      status: "active",
    },
    {
      id: "2",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Extra Job",
      datePosted: "2025-01-15",
      applicants: 5,
      views: 120,
      status: "active",
    },
    {
      id: "3",
      jobTitle: "Senior UI/UX Designer",
      jobType: "Part time",
      datePosted: "2024-12-20",
      applicants: 10,
      views: 80,
      status: "closed",
    },
    {
      id: "4",
      jobTitle: "Frontend Developer",
      jobType: "Full time",
      datePosted: "2025-02-05",
      applicants: 15,
      views: 200,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
    {
      id: "5",
      jobTitle: "Product Manager",
      jobType: "Full time",
      datePosted: "2025-01-28",
      applicants: 8,
      views: 95,
      status: "active",
    },
  ]

  export default mockJobListingsData;